add debug logs

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -79,8 +79,10 @@ jobs:
               sleep 10
               ALL_LABELS=$(curl -s -H "Authorization: Bearer ${{ env.GITHUB_TOKEN }}" "${{ env.ISSUE_ENDPOINT  }}/labels" | jq -r '.[].name')
               if [[ $ALL_LABELS == *"${{ env.PASS_LABEL }}"* ]]; then
+                  echo "job2 passed" >&2
                   exit 0
               elif [[ $ALL_LABELS == *"${{ env.FAIL_LABEL }}"* ]]; then
+                echo "job2 failed" >&2
                 exit 1
               else
                 echo "Waiting for the job2-pass or job2-fail label..."
