asd

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -9,6 +9,7 @@ env:
   RERUN_START_LABEL: rerun-command # hard coded in label-initialization run condition
   GITHUB_REPO_API: ${{ github.api_url }}/repos/${{ github.repository }}
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  ASYNC_JOB_LABELS: job2-pass job2-fail job2-pending
 
 concurrency:
   group: ${{ github.repository }}-${{ github.event.pull_request.number }}
@@ -19,19 +20,25 @@ permissions:
   pull-requests: write
   actions: write
 jobs:
-  trigger-guard:
+  trigger-guard-1:
     # This job:
     # - Prevents new runs until an other run is completed
     # - Allows rerun via the RERUN_START_LABEL label
     runs-on: ubuntu-latest
     env:
       can-run: false
+    outputs:
+      can-run: ${{ env.can-run }}
     steps:
       - name: Deny if async job is pending (rerun when job is done)
         if: ${{ contains(github.event.pull_request.labels.*.name, '-pending') }}
         run: |
           echo "Async job is still executing. Cannot start a new run."
-          gh pr edit ${{ github.event.pull_request.number }} --add-label ${{ env.RERUN_REQUEST_LABEL }}
+          curl \
+            -X POST \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "${{ env.GITHUB_REPO_API }}/issues/${{ github.event.pull_request.number }}/labels" \
+            -d '{"labels":["${{ env.RERUN_REQUEST_LABEL }}"]}'
           exit 1
 
       - name: On commit like event
@@ -41,7 +48,6 @@ jobs:
         if: ${{ github.event.action == 'labeled' && github.event.label.name == env.RERUN_START_LABEL }}
         run: |
           echo 'can-run=true' >> $GITHUB_ENV
-          gh pr edit ${{ github.event.pull_request.number }} --remove-label ${{ env.RERUN_START_LABEL }}
 
       - name: Cancel if cannot run
         run: |
@@ -54,78 +60,87 @@ jobs:
             exit 1
           fi
 
-  reset-labels:
+  reset-labels-2:
     runs-on: ubuntu-latest
-    needs: [trigger-guard]
+    needs: [trigger-guard-1]
+    if: ${{ needs.trigger-guard-1.outputs.can-run == 'true' }}
     steps:
       - name: Remove labels from previous runs
         run: |
-          gh pr edit ${{ github.event.pull_request.number }} \
-            --remove-label job2-pass \
-            --remove-label job2-fail \
-            --remove-label job2-pending
+          for label in ${{ env.ASYNC_JOB_LABELS }} ${{ env.RERUN_START_LABEL }}
+          do
+            curl \
+              -X DELETE \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              "${{ env.GITHUB_REPO_API }}/issues/${{ github.event.pull_request.number }}/labels/$label"
+          done
 
-  check-1:
+  check-100:
     runs-on: [ubuntu-latest]
-    needs: [trigger-guard, reset-labels]
+    needs: [reset-labels-2]
     steps:
-      - name: Execute Check 1
+      - name: Execute Check 100
         run: |
-          echo "Check 1 is executing..."
-          echo "Check 1 passed." || exit 1
+          echo "Check 100 is executing..."
+          echo "Check 100 passed." || exit 1
+      - name: Execute Check 101
+        run: |
+          echo "Check 101 is executing..."
+          echo "Check 101 passed." || exit 1
 
-  check-2:
+  check-200_trigger:
     runs-on: [ubuntu-latest]
-    needs: [check-1]
+    needs: [check-100]
     steps:
-      - name: Execute Check 2
+      - name: Trigger Check 200
         run: |
-          echo "Check 2 is executing..."
-          echo "Check 2 passed." || exit 1
-
-  check-10_trigger:
-    runs-on: [ubuntu-latest]
-    needs: [check-2]
-    steps:
-      - name: Trigger Check 10
-        run: |
-          echo "Check 10 is starting..."
-          gh pr edit ${{ github.event.pull_request.number }} --add-label job2-pending
-          echo "Check 2 started." || exit 1
+          echo "Check 200 is starting..."
+          curl \
+            -X POST \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "${{ env.GITHUB_REPO_API }}/issues/${{ github.event.pull_request.number }}/labels" \
+            -d '{"labels":["job2-pending"]}'
+          echo "Check 200 started." || exit 1
           echo "Goodbye and see you soon!"
-  check-10_join:
+  check-200_join:
     runs-on: [ubuntu-latest]
     if: ${{ contains('job2-pass job2-fail', github.event.label.name) }}
     steps:
       - name: Workflow is no longer up to date. Requesting a rerun.
         if: ${{ contains(github.event.pull_request.labels.*.name, env.RERUN_REQUEST_LABEL) }}
         run: |
-          echo "Check 10 is no longer up to date. Requesting a rerun."
-          gh pr edit ${{ github.event.pull_request.number }} \
-            --remove-label ${{ env.RERUN_REQUEST_LABEL }} \
-            --add-label ${{ env.RERUN_START_LABEL }}
+          echo "Workflow is no longer up to date. Requesting a rerun."
+          curl \
+            -X POST \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "${{ env.GITHUB_REPO_API }}/issues/${{ github.event.pull_request.number }}/labels" \
+            -d '{"labels":["${{ env.RERUN_START_LABEL }}"]}'
+          curl \
+            -X DELETE \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            "${{ env.GITHUB_REPO_API }}/issues/${{ github.event.pull_request.number }}/labels/${{ env.RERUN_REQUEST_LABEL }}"
           exit 1
+
       - name: Fail if result is fail
         if: ${{ github.event.label.name == 'job2-fail' }}
-        run: echo "Check 10 failed." ; exit 1
+        run: echo "Background job failed." ; exit 1
+
       - name: Remove labels
         run: |
-          gh pr edit ${{ github.event.pull_request.number }} \
-            --remove-label job2-pending --remove-label job2-pass --remove-label job2-fail
+          for label in job2-pending job2-pass job2-fail
+          do
+            curl \
+              -X DELETE \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              "${{ env.GITHUB_REPO_API }}/issues/${{ github.event.pull_request.number }}/labels/$label"
+          done
 
-  check-20:
-    runs-on: [ubuntu-latest]
-    needs: [check-10_join]
-    steps:
-      - name: Execute Check 20
+      - name: Execute Check 200
         run: |
-          echo "Check 20 is executing..."
-          echo "Check 20 passed." || exit 1
-  check-21:
-    runs-on: [ubuntu-latest]
-    needs: [check-20]
-    steps:
-      - name: Execute Check 21
+          echo "Check 200 is executing..."
+          echo "Check 200 passed." || exit 1
+
+      - name: Execute Check 201
         run: |
-          echo "Check 21 is executing..."
-          echo "Check 21 passed." || exit 1
+          echo "Check 201 is executing..."
+          echo "Check 201 passed." || exit 1
